server:
    port: 8081
spring:
    application:
        name: service-student
    profiles:
        active: development
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/student_db
        username: root
        password:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: true
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8099/eureka/
management:
    endpoints:
        web:
            exposure:
                include: "*"
